name: flutter_country_code_picker_example
description: Example for flutter_country_code_picker
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_country_code_picker:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
