name: flutter_country_code_picker
description: A Flutter package picking country codes, with searching and favourites.
version: 2.0.0
homepage: https://github.com/Cretezy/flutter_country_code_picker

environment:
  sdk: ">=2.5.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - flags/
